### ISSUE TITLE
Usage of paper button import in /client/main.html

### ISSUE THREAD

**Issue by iSuslov** [meteorwebcomponents/synthesis-demo#1]
What is the purpose of importing 

`<link rel="import" href="bower_components/paper-button/paper-button.html"/>`

in main.html ?
I'm trying to get polymer shop demo working but no success. And your demo seems to have some unused elements which makes it confusing

**Comment by aruntk** [comment]
sorry for not updating the demo. Please refer this demo https://github.com/aruntk/kickstart-meteor-polymer.

I've imported paper button because its used here https://github.com/meteorwebcomponents/synthesis-demo/blob/master/client/test-element.html#L3

**Comment by aruntk** [comment]
@iSuslov check the repo now. I've updated the repo. :)
